### ISSUE TITLE
Postorder traversal using Query API returns duplicate nodes

### ISSUE THREAD

**Issue by Onso37** [specs-feup/clava#155] opened 2024-07-09 13:32 UTC
```js
const jps = Query.searchFrom(exprRoot, "unaryOp", {kind: /(post_inc)|(post_dec)|(pre_inc)|(pre_dec)/}, TraversalType.POSTORDER).get();
```

Using this query with the following code:

```cpp
int a,b,c;
a = ++b + c++;
(++b)++;
```

For the first expression, sub-expression nodes `++b` and `c++` are returned twice.
For the second expression, the root itself (`(++b)++`) is also returned, such that using searchFromInclusive would lead to a duplicate result.

**Comment by lm-sousa** [comment] 2024-07-15 00:00
You describe issues with the Query API for two expressions. 

1. As for the first, I cannot reproduce the issue you described with your code snnipet. I get the expected output. Nothing is duplicated.
2. In the second expression, the output is correct. `(++b)++` is indeed a valid result. Note that the root node (ExprStmt) and the first UnaryOp in that statement correspond to the same string in the C/C++ code but they are not _"the same"_. AST dump below:

            Joinpoint 'exprStmt'
               Joinpoint 'unaryOp'
                  Joinpoint 'parenExpr'
                     Joinpoint 'unaryOp'
                        Joinpoint 'varref'

**Comment by lm-sousa** [comment] 2024-07-17 17:53
Was able to reproduce (1).
Fixed in https://github.com/specs-feup/lara-framework/commit/972f6caa0f42ccb0f9fd0369d5a333c4ded48e00

**Closed by lm-sousa** 2024-07-17 17:53 UTC
